name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linters:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test
      - name: Run isort
        run: |
          isort . -c
      - name: Run flake8
        run: |
          python -m flake8 --config=.flake8
          
